server:
  port: 8080
  servelet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgressql.Driver
    url: jbdc:postgressql://localhost:5432/postgres
    username: postgres
    password: 123456

    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: false
      hibernate:

        ddl-auto: nome

        application:
          description: Projeto criado para bootcamp dio e santader


